In [1]:
# Basic QXYCell workflow
#
# Replace the example paths below with your own QuPath export/input folder
# and QXYCell output folder.
#
# Expected input folder contents:
# - measurements.csv or measurements.tsv
# - GeoJSON annotation files
# - optional object classifier JSON files
# - optional active threshold table, such as thresholds.tsv
#
# Threshold workflow:
# - Generated threshold templates are written to output_dir / tables.
# - The active user-edited threshold table should live in project_dir.
# - qxy.run() uses the newest recognized threshold table in project_dir by default.
# - Pass threshold_file=... to force a specific threshold table.

from pathlib import Path

import pandas as pd
import qxycell as qxy

pd.set_option("display.max_columns", 80)
pd.set_option("display.max_rows", 30)

In [2]:
# 1. Set project paths.
# project_dir is the QuPath export/input folder.
# output_dir is where QXYCell writes reports, generated threshold templates,
# plots, and saved H5AD files.

project_dir = Path("/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input")
output_dir = Path("/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs")

project_dir, output_dir

(PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input'),
 PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs'))

In [3]:
# 2. Inspect available input files.

input_files = sorted(
    p.relative_to(project_dir)
    for p in project_dir.rglob("*")
    if p.is_file()
)

input_files[:50]

[PosixPath('.DS_Store'),
 PosixPath('02_input_readme.txt'),
 PosixPath('COMET_2025_TMA1-4_Patient IDs.xlsx'),
 PosixPath('CoreID.csv'),
 PosixPath('PatientMetaData.csv'),
 PosixPath('celltype_logic_260617.yaml'),
 PosixPath('qupath_annotations/TMA1_r1.geojson'),
 PosixPath('qupath_annotations/TMA2_r1.geojson'),
 PosixPath('qupath_annotations/TMA3_r1.geojson'),
 PosixPath('qupath_annotations/TMA4_r1.geojson'),
 PosixPath('qupath_annotations/qupath_annotations_readme.txt'),
 PosixPath('qupath_feature_measurements/TMA1_features_measurements.csv'),
 PosixPath('qupath_feature_measurements/TMA2_features_measurements.csv'),
 PosixPath('qupath_feature_measurements/TMA3_features_measurements.csv'),
 PosixPath('qupath_feature_measurements/TMA4_features_measurements.csv'),
 PosixPath('qupath_feature_measurements/qupath_feature_measurements_readme.txt'),
 PosixPath('thresholds.tsv')]

In [4]:
# 3. Generate a threshold table template from object classifiers.
# This creates a fresh timestamped table in output_dir / tables.
# It does not modify an existing threshold table in project_dir.

generated_threshold_table = qxy.generate_threshold_table(
    project_dir,
    output_dir=output_dir,
)

generated_threshold_table

PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/tables/thresholds_260622-1616.tsv')

In [6]:
# 4. Select the active threshold table.
#
# After reviewing or editing the generated table, place the active threshold
# table in project_dir. The simplest active filename is thresholds.tsv.
#
# Leave threshold_file = None to auto-select the newest recognized threshold
# table in project_dir. Set threshold_file explicitly to force one file.

threshold_file = None

# Example explicit source:
# threshold_file = project_dir / "thresholds.tsv"

threshold_file

In [7]:
# 5. Run QXYCell check.
#
# qxy.check() validates measurements, threshold definitions, and GeoJSON files.
# It also writes a fresh JSON-derived threshold template to output_dir / tables
# when object classifier JSONs are present.

report = qxy.check(
    project_dir,
    output_dir=output_dir,
    #threshold_file=threshold_file,
    count_rows=True,
)

report

QXYCell check report
Project: /Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input
Output: /Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs
Status: PASS
Errors: 0
Warnings: 252

Measurement files: 4
Classifier definitions: 364
  Simple classifiers: 112
  Markers: aSMA, aSMA, aSMA, aSMA, CD14_, CD14_, CD14_, CD14_, CD16, CD16, CD16, CD16, CD1c, CD1c, CD1c, CD1c, CD20, CD20, CD20, CD20, CD206, CD206, CD206, CD206, CD3, CD3, CD3, CD3, CD31, CD31, CD31, CD31, CD4, CD4, CD4, CD4, CD45, CD45, CD45, CD45, CD45RA, CD45RA, CD45RA, CD45RA, CD56, CD56, CD56, CD56, CD68, CD68, CD68, CD68, CD8, CD8, CD8, CD8, CK8_, CK8_, CK8_, CK8_, DAPI, DAPI, DAPI, DAPI, FAP, FAP, FAP, FAP, FXIIIa, FXIIIa, FXIIIa, FXIIIa, HLADR, HLADR, HLADR, HLADR, HepPar1, HepPar1, HepPar1, HepPar1, Ki-67, Ki-67, Ki-67, Ki-67, MPO_, MPO_, MPO_, MPO_, NaKATPase, NaKATPase, NaKATPase, NaKATPase, PD-1, PD-1, PD-1, PD-1, PD-L1, PD-L1, PD-L1, PD-L1, VE-Cadherin, VE-Cadherin, VE-Cadherin, VE-Cadherin, VEGF, VEGF, VEGF, VEGF, vimentin, vimentin, vimentin, vimentin
  Manual threshold template: /Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/tables/thresholds_260622-1616.tsv
GeoJSON files: 4
GeoJSON object counts:
  Annotation features: 207
  QuPath tmaCore objects: 0
  Cell features     : 0
Measurement derived TMA CoreIDs:
  Unique CoreIDs    : 120
  Assigned cells    : 756854
  CoreIDs           : 1-E3 (7498), 1-E4 (6493), 1-E5 (4585), 1-E6 (7902), 1-F1 (6673), 1-F2 (3215), 1-F3 (7045), 1-F4 (5784), 1-F5 (5874), 1-F6 (4838), 1-G1 (4429), 1-G2 (3136), 1-G3 (14355), 1-G4 (8324), 1-H2 (8172), 1-H3 (4971), 1-H5 (7518), 1-H6 (6273), 1-I1 (6729), 1-I2 (4061), 1-I3 (6304), 1-I4 (6458), 1-I5 (5886), 1-I6 (5286), 1-J1 (6143), 1-J2 (4818), 1-J3 (5064), 1-J4 (4358), 1-J5 (9047), 1-J6 (4232), 2-A1 (7851), 2-A2 (4494), 2-A3 (4520), 2-A4 (6676), 2-A5 (5647), 2-A6 (4084), 2-B2 (3261), 2-B3 (10726), 2-B4 (8694), 2-B5 (10147), 2-B6 (7236), 2-C1 (5412), 2-C2 (6502), 2-C3 (5766), 2-C4 (5129), 2-C5 (4007), 2-D1 (3762), 2-D2 (5149), 2-D3 (6251), 2-D4 (5726), 2-D5 (5466), 2-D6 (5534), 2-E1 (6439), 2-E2 (4728), 2-E3 (5074), 2-E4 (4388), 2-E5 (4242), 2-E6 (9069), 2-F1 (8606), 2-F2 (7426), 2-F3 (9718), 2-F4 (7537), 2-F5 (7338), 2-G1 (2731), 2-G2 (5388), 2-G3 (15367), 2-G4 (5201), 3-G3 (19007), 3-G4 (4496), 3-G5 (8425), 3-G6 (4381), 3-H1 (5868), 3-H2 (5507), 3-H3 (6545), 3-H4 (6312), 3-I1 (2390), 3-K2 (3965), 3-L2 (5335), 3-L3 (5245), 3-L4 (5554), 3-M3 (3242), 3-M6 (13425), G-1 (4658), G-2 (4940), G-3 (15732), G-4 (6719), G-5 (4300), G-6 (1903), H-1 (5261), H-2 (6744), H-3 (5650), H-4 (4627), H-5 (8102), H-6 (8425), I-1 (3533), I-2 (3155), I-3 (3991), I-5 (6101), I-6 (7633), J-1 (6381), J-2 (6445), J-3 (5555), J-4 (5587), J-5 (5473), J-6 (5713), K-1 (5684), K-2 (5899), K-3 (6205), K-4 (6593), K-5 (6755), K-6 (9158), L-1 (2292), L-2 (6529), L-3 (5893), L-4 (5880), L-5 (4784), L-6 (6753), M-1 (5590), M-5 (7351), M-6 (14400)
GeoJSON derived TMA CoreIDs:
  Unique CoreIDs    : 81
  GeoJSON features  : 81
  CoreIDs           : 1-E3 (1), 1-E4 (1), 1-E5 (1), 1-E6 (1), 1-F1 (1), 1-F2 (1), 1-F3 (1), 1-F4 (1), 1-F5 (1), 1-F6 (1), 1-G1 (1), 1-G2 (1), 1-G3 (1), 1-G4 (1), 1-H2 (1), 1-H3 (1), 1-H5 (1), 1-H6 (1), 1-I1 (1), 1-I2 (1), 1-I3 (1), 1-I4 (1), 1-I5 (1), 1-I6 (1), 1-J1 (1), 1-J2 (1), 1-J3 (1), 1-J4 (1), 1-J5 (1), 1-J6 (1), 2-A1 (1), 2-A2 (1), 2-A3 (1), 2-A4 (1), 2-A5 (1), 2-A6 (1), 2-B2 (1), 2-B3 (1), 2-B4 (1), 2-B5 (1), 2-B6 (1), 2-C1 (1), 2-C2 (1), 2-C3 (1), 2-C4 (1), 2-C5 (1), 2-D1 (1), 2-D2 (1), 2-D3 (1), 2-D4 (1), 2-D5 (1), 2-D6 (1), 2-E2 (1), 2-E3 (1), 2-E4 (1), 2-E5 (1), 2-E6 (1), 2-F1 (1), 2-F2 (1), 2-F3 (1), 2-F4 (1), 2-F5 (1), 2-G1 (1), 2-G2 (1), 2-G3 (1), 2-G4 (1), 3-G3 (1), 3-G4 (1), 3-G5 (1), 3-G6 (1), 3-H1 (1), 3-H2 (1), 3-H3 (1), 3-H4 (1), 3-I1 (1), 3-K2 (1), 3-L2 (1), 3-L3 (1), 3-L4 (1), 3-M3 (1), 3-M6 (1)
  Matched measurement CoreIDs: 1-E3 (1), 1-E4 (1), 1-E5 (1), 1-E6 (1), 1-F1 (1), 1-F2 (1), 1-F3 (1), 1-F4 (1), 1-F5 (1), 1-F6 (1), 1-G1 (1), 1-G2 (1), 1-G3 (1), 1-G4 (1), 1-H2 (1), 1-H3 (1), 1-H5 (1), 1-H6 (1), 1-I1 (1), 1-I2 (1), 1-I3 (1), 1-I4 (1), 1-I5 (1), 1-I6 (1), 1-J1 (1), 1-J2 (1), 1-J3 (1), 1-J4 (1), 1-J5 (1), 1-J6 (1), 2-A1 (1), 2-A2 (1), 2-A3 (1), 2-A4 (1), 2-A5 (1), 2-A6 (1), 2-B2 (1), 2-B3 (1), 2-B4 (1), 2-B5 (1), 2-B6 (1), 2-C1 (1), 2-C2 (1), 2-C3 (1), 2-C4 (1), 2-C5 (1), 2-D1 (1), 2-D2 (1), 2-D3 (1), 2-D4 (1), 2-D5 (1), 2-D6 (1), 2-E2 (1), 2-E3 (1), 2-E4 (1), 2-E5 (1), 2-E6 (1), 2-F1 (1), 2-F2 (1), 2-F3 (1), 2-F4 (1), 2-F5 (1), 2-G1 (1), 2-G2 (1), 2-G3 (1), 2-G4 (1), 3-G3 (1), 3-G4 (1), 3-G5 (1), 3-G6 (1), 3-H1 (1), 3-H2 (1), 3-H3 (1), 3-H4 (1), 3-I1 (1), 3-K2 (1), 3-L2 (1), 3-L3 (1), 3-L4 (1), 3-M3 (1), 3-M6 (1)
  Measurement-only  : 2-E1 (6439), G-1 (4658), G-2 (4940), G-3 (15732), G-4 (6719), G-5 (4300), G-6 (1903), H-1 (5261), H-2 (6744), H-3 (5650), H-4 (4627), H-5 (8102), H-6 (8425), I-1 (3533), I-2 (3155), I-3 (3991), I-5 (6101), I-6 (7633), J-1 (6381), J-2 (6445), J-3 (5555), J-4 (5587), J-5 (5473), J-6 (5713), K-1 (5684), K-2 (5899), K-3 (6205), K-4 (6593), K-5 (6755), K-6 (9158), L-1 (2292), L-2 (6529), L-3 (5893), L-4 (5880), L-5 (4784), L-6 (6753), M-1 (5590), M-5 (7351), M-6 (14400)

Annotations:
  Sample   : none
  Ignore   : Ignore* (126)
  Other    : HCA (4), IM (22), NT (24), Tonsil (5), Tumor (26)
TMA cores: none
  Cell labels: none

Messages:
- INFO tma.measurement_core_ids_preferred: GeoJSON annotation labels matching measurement core IDs were found. qxy.run() uses measurement CoreID values and does not keep those matching labels as annotation columns.
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row2' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row2]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row4' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row4]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row5' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row5]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row6' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row6]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row8' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row8]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row10' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row10]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row11' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row11]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row12' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row12]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row14' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row14]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row16' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row16]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row18' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row18]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row20' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row20]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row22' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row22]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row23' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row23]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row24' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row24]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row26' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row26]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row28' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row28]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row30' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row30]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row32' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row32]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row33' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row33]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row34' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row34]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row36' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row36]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row38' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row38]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row40' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row40]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row42' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row42]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row44' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row44]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row46' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row46]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row47' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row47]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row48' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row48]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row50' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row50]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row52' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row52]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row54' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row54]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row56' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row56]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row58' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row58]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row60' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row60]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row62' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row62]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row63' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row63]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row64' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row64]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row66' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row66]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row68' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row68]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row69' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row69]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row70' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row70]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row72' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row72]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row73' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row73]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row74' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row74]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row75' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row75]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row76' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row76]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row77' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row77]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row78' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row78]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row79' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row79]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row80' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row80]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row81' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row81]

QXYCell check: PASS
Errors: 0
Warnings: 252
Measurement files: 4
Classifier definitions: 364
Simple classifiers: 112
GeoJSON files: 4
Annotation features: 207
Measurement derived TMA CoreIDs: 120
GeoJSON derived TMA CoreIDs: 81
Cell features: 0
Report: /Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/check_report.txt

In [8]:
# Inspect check messages.

pd.DataFrame([m.to_dict() for m in report.messages])

,level,code,message,path
0,warning,classifiers.unsupported,Classifier 'thresholds.tsv#row2' is not a simp...,/Users/json/Desktop/1_Projects/251128_XYCellty...
1,warning,classifiers.unsupported,Classifier 'thresholds.tsv#row4' is not a simp...,/Users/json/Desktop/1_Projects/251128_XYCellty...
2,warning,classifiers.unsupported,Classifier 'thresholds.tsv#row5' is not a simp...,/Users/json/Desktop/1_Projects/251128_XYCellty...
3,warning,classifiers.unsupported,Classifier 'thresholds.tsv#row6' is not a simp...,/Users/json/Desktop/1_Projects/251128_XYCellty...
4,warning,classifiers.unsupported,Classifier 'thresholds.tsv#row8' is not a simp...,/Users/json/Desktop/1_Projects/251128_XYCellty...
...,...,...,...,...
247,warning,classifiers.unsupported,Classifier 'thresholds.tsv#row277' is not a si...,/Users/json/Desktop/1_Projects/251128_XYCellty...
248,warning,classifiers.unsupported,Classifier 'thresholds.tsv#row278' is not a si...,/Users/json/Desktop/1_Projects/251128_XYCellty...
249,warning,classifiers.unsupported,Classifier 'thresholds.tsv#row279' is not a si...,/Users/json/Desktop/1_Projects/251128_XYCellty...
250,warning,classifiers.unsupported,Classifier 'thresholds.tsv#row280' is not a si...,/Users/json/Desktop/1_Projects/251128_XYCellty...
251,warning,classifiers.unsupported,Classifier 'thresholds.tsv#row281' is not a si...,/Users/json/Desktop/1_Projects/251128_XYCellty...

In [9]:
# 6. Run import to AnnData.

adata = qxy.run(
    project_dir,
    output_dir=output_dir,
    threshold_file=threshold_file,
    pixel_size_um=0.28,
)

adata

QXYCell run started
Project: /Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input
Output: /Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs
QXYCell check report
Project: /Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input
Output: /Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs
Status: PASS
Errors: 0
Warnings: 252

Measurement files: 4
Classifier definitions: 364
  Simple classifiers: 112
  Markers: aSMA, aSMA, aSMA, aSMA, CD14_, CD14_, CD14_, CD14_, CD16, CD16, CD16, CD16, CD1c, CD1c, CD1c, CD1c, CD20, CD20, CD20, CD20, CD206, CD206, CD206, CD206, CD3, CD3, CD3, CD3, CD31, CD31, CD31, CD31, CD4, CD4, CD4, CD4, CD45, CD45, CD45, CD45, CD45RA, CD45RA, CD45RA, CD45RA, CD56, CD56, CD56, CD56, CD68, CD68, CD68, CD68, CD8, CD8, CD8, CD8, CK8_, CK8_, CK8_, CK8_, DAPI, DAPI, DAPI, DAPI, FAP, FAP, FAP, FAP, FXIIIa, FXIIIa, FXIIIa, FXIIIa, HLADR, HLADR, HLADR, HLADR, HepPar1, HepPar1, HepPar1, HepPar1, Ki-67, Ki-67, Ki-67, Ki-67, MPO_, MPO_, MPO_, MPO_, NaKATPase, NaKATPase, NaKATPase, NaKATPase, PD-1, PD-1, PD-1, PD-1, PD-L1, PD-L1, PD-L1, PD-L1, VE-Cadherin, VE-Cadherin, VE-Cadherin, VE-Cadherin, VEGF, VEGF, VEGF, VEGF, vimentin, vimentin, vimentin, vimentin
  Manual threshold template: /Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/tables/thresholds_260622-1616.tsv
GeoJSON files: 4
GeoJSON object counts:
  Annotation features: 207
  QuPath tmaCore objects: 0
  Cell features     : 0
Measurement derived TMA CoreIDs:
  Unique CoreIDs    : 120
  Assigned cells    : 756854
  CoreIDs           : 1-E3 (7498), 1-E4 (6493), 1-E5 (4585), 1-E6 (7902), 1-F1 (6673), 1-F2 (3215), 1-F3 (7045), 1-F4 (5784), 1-F5 (5874), 1-F6 (4838), 1-G1 (4429), 1-G2 (3136), 1-G3 (14355), 1-G4 (8324), 1-H2 (8172), 1-H3 (4971), 1-H5 (7518), 1-H6 (6273), 1-I1 (6729), 1-I2 (4061), 1-I3 (6304), 1-I4 (6458), 1-I5 (5886), 1-I6 (5286), 1-J1 (6143), 1-J2 (4818), 1-J3 (5064), 1-J4 (4358), 1-J5 (9047), 1-J6 (4232), 2-A1 (7851), 2-A2 (4494), 2-A3 (4520), 2-A4 (6676), 2-A5 (5647), 2-A6 (4084), 2-B2 (3261), 2-B3 (10726), 2-B4 (8694), 2-B5 (10147), 2-B6 (7236), 2-C1 (5412), 2-C2 (6502), 2-C3 (5766), 2-C4 (5129), 2-C5 (4007), 2-D1 (3762), 2-D2 (5149), 2-D3 (6251), 2-D4 (5726), 2-D5 (5466), 2-D6 (5534), 2-E1 (6439), 2-E2 (4728), 2-E3 (5074), 2-E4 (4388), 2-E5 (4242), 2-E6 (9069), 2-F1 (8606), 2-F2 (7426), 2-F3 (9718), 2-F4 (7537), 2-F5 (7338), 2-G1 (2731), 2-G2 (5388), 2-G3 (15367), 2-G4 (5201), 3-G3 (19007), 3-G4 (4496), 3-G5 (8425), 3-G6 (4381), 3-H1 (5868), 3-H2 (5507), 3-H3 (6545), 3-H4 (6312), 3-I1 (2390), 3-K2 (3965), 3-L2 (5335), 3-L3 (5245), 3-L4 (5554), 3-M3 (3242), 3-M6 (13425), G-1 (4658), G-2 (4940), G-3 (15732), G-4 (6719), G-5 (4300), G-6 (1903), H-1 (5261), H-2 (6744), H-3 (5650), H-4 (4627), H-5 (8102), H-6 (8425), I-1 (3533), I-2 (3155), I-3 (3991), I-5 (6101), I-6 (7633), J-1 (6381), J-2 (6445), J-3 (5555), J-4 (5587), J-5 (5473), J-6 (5713), K-1 (5684), K-2 (5899), K-3 (6205), K-4 (6593), K-5 (6755), K-6 (9158), L-1 (2292), L-2 (6529), L-3 (5893), L-4 (5880), L-5 (4784), L-6 (6753), M-1 (5590), M-5 (7351), M-6 (14400)
GeoJSON derived TMA CoreIDs:
  Unique CoreIDs    : 81
  GeoJSON features  : 81
  CoreIDs           : 1-E3 (1), 1-E4 (1), 1-E5 (1), 1-E6 (1), 1-F1 (1), 1-F2 (1), 1-F3 (1), 1-F4 (1), 1-F5 (1), 1-F6 (1), 1-G1 (1), 1-G2 (1), 1-G3 (1), 1-G4 (1), 1-H2 (1), 1-H3 (1), 1-H5 (1), 1-H6 (1), 1-I1 (1), 1-I2 (1), 1-I3 (1), 1-I4 (1), 1-I5 (1), 1-I6 (1), 1-J1 (1), 1-J2 (1), 1-J3 (1), 1-J4 (1), 1-J5 (1), 1-J6 (1), 2-A1 (1), 2-A2 (1), 2-A3 (1), 2-A4 (1), 2-A5 (1), 2-A6 (1), 2-B2 (1), 2-B3 (1), 2-B4 (1), 2-B5 (1), 2-B6 (1), 2-C1 (1), 2-C2 (1), 2-C3 (1), 2-C4 (1), 2-C5 (1), 2-D1 (1), 2-D2 (1), 2-D3 (1), 2-D4 (1), 2-D5 (1), 2-D6 (1), 2-E2 (1), 2-E3 (1), 2-E4 (1), 2-E5 (1), 2-E6 (1), 2-F1 (1), 2-F2 (1), 2-F3 (1), 2-F4 (1), 2-F5 (1), 2-G1 (1), 2-G2 (1), 2-G3 (1), 2-G4 (1), 3-G3 (1), 3-G4 (1), 3-G5 (1), 3-G6 (1), 3-H1 (1), 3-H2 (1), 3-H3 (1), 3-H4 (1), 3-I1 (1), 3-K2 (1), 3-L2 (1), 3-L3 (1), 3-L4 (1), 3-M3 (1), 3-M6 (1)
  Matched measurement CoreIDs: 1-E3 (1), 1-E4 (1), 1-E5 (1), 1-E6 (1), 1-F1 (1), 1-F2 (1), 1-F3 (1), 1-F4 (1), 1-F5 (1), 1-F6 (1), 1-G1 (1), 1-G2 (1), 1-G3 (1), 1-G4 (1), 1-H2 (1), 1-H3 (1), 1-H5 (1), 1-H6 (1), 1-I1 (1), 1-I2 (1), 1-I3 (1), 1-I4 (1), 1-I5 (1), 1-I6 (1), 1-J1 (1), 1-J2 (1), 1-J3 (1), 1-J4 (1), 1-J5 (1), 1-J6 (1), 2-A1 (1), 2-A2 (1), 2-A3 (1), 2-A4 (1), 2-A5 (1), 2-A6 (1), 2-B2 (1), 2-B3 (1), 2-B4 (1), 2-B5 (1), 2-B6 (1), 2-C1 (1), 2-C2 (1), 2-C3 (1), 2-C4 (1), 2-C5 (1), 2-D1 (1), 2-D2 (1), 2-D3 (1), 2-D4 (1), 2-D5 (1), 2-D6 (1), 2-E2 (1), 2-E3 (1), 2-E4 (1), 2-E5 (1), 2-E6 (1), 2-F1 (1), 2-F2 (1), 2-F3 (1), 2-F4 (1), 2-F5 (1), 2-G1 (1), 2-G2 (1), 2-G3 (1), 2-G4 (1), 3-G3 (1), 3-G4 (1), 3-G5 (1), 3-G6 (1), 3-H1 (1), 3-H2 (1), 3-H3 (1), 3-H4 (1), 3-I1 (1), 3-K2 (1), 3-L2 (1), 3-L3 (1), 3-L4 (1), 3-M3 (1), 3-M6 (1)
  Measurement-only  : 2-E1 (6439), G-1 (4658), G-2 (4940), G-3 (15732), G-4 (6719), G-5 (4300), G-6 (1903), H-1 (5261), H-2 (6744), H-3 (5650), H-4 (4627), H-5 (8102), H-6 (8425), I-1 (3533), I-2 (3155), I-3 (3991), I-5 (6101), I-6 (7633), J-1 (6381), J-2 (6445), J-3 (5555), J-4 (5587), J-5 (5473), J-6 (5713), K-1 (5684), K-2 (5899), K-3 (6205), K-4 (6593), K-5 (6755), K-6 (9158), L-1 (2292), L-2 (6529), L-3 (5893), L-4 (5880), L-5 (4784), L-6 (6753), M-1 (5590), M-5 (7351), M-6 (14400)

Annotations:
  Sample   : none
  Ignore   : Ignore* (126)
  Other    : HCA (4), IM (22), NT (24), Tonsil (5), Tumor (26)
TMA cores: none
  Cell labels: none

Messages:
- INFO tma.measurement_core_ids_preferred: GeoJSON annotation labels matching measurement core IDs were found. qxy.run() uses measurement CoreID values and does not keep those matching labels as annotation columns.
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row2' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row2]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row4' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row4]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row5' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row5]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row6' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row6]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row8' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row8]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row10' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row10]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row11' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row11]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row12' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row12]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row14' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row14]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row16' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row16]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row18' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row18]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row20' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row20]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row22' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row22]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row23' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row23]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row24' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row24]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row26' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row26]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row28' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row28]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row30' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row30]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row32' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row32]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row33' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row33]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row34' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row34]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row36' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row36]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row38' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row38]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row40' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row40]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row42' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row42]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row44' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row44]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row46' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row46]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row47' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row47]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row48' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row48]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row50' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row50]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row52' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row52]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row54' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row54]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row56' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row56]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row58' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row58]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row60' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row60]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row62' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row62]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row63' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row63]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row64' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row64]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row66' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row66]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row68' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row68]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row69' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row69]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row70' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row70]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row72' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row72]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row73' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row73]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row74' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row74]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row75' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row75]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row76' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row76]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row77' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row77]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row78' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row78]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row79' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row79]
- WARNING classifiers.unsupported: Classifier 'thresholds.tsv#row80' is not a simple single-measurement threshold definition and will be skipped in v1 (invalid_manual_threshold_row). [/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/thresholds.tsv#row80]

AnnData object with n_obs × n_vars = 756854 × 28
    obs: 'Image', 'Object ID', 'Xµm', 'Yµm', 'TMA Core', 'Parent', 'quxy_source_file', 'quxy_source_row', 'quxy_cell_id', 'aSMA_pos', 'CD14_pos', 'CD16_pos', 'CD1c_pos', 'CD20_pos', 'CD206_pos', 'CD3_pos', 'CD31_pos', 'CD4_pos', 'CD45_pos', 'CD45RA_pos', 'CD56_pos', 'CD68_pos', 'CD8_pos', 'CK8_pos', 'DAPI_pos', 'FAP_pos', 'FXIIIa_pos', 'HLADR_pos', 'HepPar1_pos', 'Ki_67_pos', 'MPO_pos', 'NaKATPase_pos', 'PD_1_pos', 'PD_L1_pos', 'VE_Cadherin_pos', 'VEGF_pos', 'vimentin_pos', 'CoreID', 'annotation__HCA', 'annotation__IM', 'annotation__Ignore', 'annotation__NT', 'annotation__Tonsil', 'annotation__Tumor'
    var: 'marker_name', 'classifier_name', 'source_measurement_column', 'threshold', 'threshold_source'
    uns: 'qxycell_core_ids_from_measurements', 'qxycell_annotation_labels', 'qxycell'
    obsm: 'spatial'

In [20]:
# Preview cell metadata.

adata.obs.head()

,Image,Object ID,Xµm,Yµm,TMA Core,Parent,quxy_source_file,quxy_source_row,quxy_cell_id,aSMA_pos,CD14_pos,CD16_pos,CD1c_pos,CD20_pos,CD206_pos,CD3_pos,CD31_pos,CD4_pos,CD45_pos,CD45RA_pos,CD56_pos,CD68_pos,CD8_pos,CK8_pos,DAPI_pos,FAP_pos,FXIIIa_pos,HLADR_pos,HepPar1_pos,Ki_67_pos,MPO_pos,NaKATPase_pos,PD_1_pos,PD_L1_pos,VE_Cadherin_pos,VEGF_pos,vimentin_pos,CoreID,annotation__HCA,annotation__IM,annotation__Ignore,annotation__NT,annotation__Tonsil,annotation__Tumor,Sample
TMA1_r1.tiff::1ca777a0-876d-48ce-b031-24664ab28cb4,TMA1_r1.tiff,1ca777a0-876d-48ce-b031-24664ab28cb4,211.17,2828.9,NaN,1-I6,/Users/json/Desktop/1_Projects/251128_XYCellty...,1,TMA1_r1.tiff::1ca777a0-876d-48ce-b031-24664ab2...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0,0,1-I6,False,True,False,False,False,False,NaN
TMA1_r1.tiff::0a90e052-042a-42e5-b532-52fdeee11709,TMA1_r1.tiff,0a90e052-042a-42e5-b532-52fdeee11709,197.75,2817.6,NaN,1-I6,/Users/json/Desktop/1_Projects/251128_XYCellty...,2,TMA1_r1.tiff::0a90e052-042a-42e5-b532-52fdeee1...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1-I6,False,True,False,False,False,False,NaN
TMA1_r1.tiff::b61cdcf7-3ecf-44fb-8566-b24912e31fa1,TMA1_r1.tiff,b61cdcf7-3ecf-44fb-8566-b24912e31fa1,211.47,2838.5,NaN,1-I6,/Users/json/Desktop/1_Projects/251128_XYCellty...,3,TMA1_r1.tiff::b61cdcf7-3ecf-44fb-8566-b24912e3...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0,0,1-I6,False,True,False,False,False,False,NaN
TMA1_r1.tiff::8007657c-683e-4354-b6fc-c942c302d50e,TMA1_r1.tiff,8007657c-683e-4354-b6fc-c942c302d50e,166.73,2855.6,NaN,1-I6,/Users/json/Desktop/1_Projects/251128_XYCellty...,4,TMA1_r1.tiff::8007657c-683e-4354-b6fc-c942c302...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0,0,1-I6,False,False,False,False,False,False,NaN
TMA1_r1.tiff::2d83a38a-94e0-41c5-acb0-9a0d48c09a1b,TMA1_r1.tiff,2d83a38a-94e0-41c5-acb0-9a0d48c09a1b,178.72,2868.0,NaN,1-I6,/Users/json/Desktop/1_Projects/251128_XYCellty...,5,TMA1_r1.tiff::2d83a38a-94e0-41c5-acb0-9a0d48c0...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0,0,1-I6,False,True,False,False,False,False,NaN

In [21]:
# Preview marker metadata and threshold sources.

adata.var

,marker_name,classifier_name,source_measurement_column,threshold,threshold_source
aSMA,aSMA,aSMA,Cell: #945;SMA - TRITC: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CD14,CD14,CD14_,Cell: CD14_ - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CD16,CD16,CD16,Cell: CD16 - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CD1c,CD1c,CD1c,Cell: CD1c - TRITC: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CD20,CD20,CD20,Cell: CD20 - TRITC: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CD206,CD206,CD206,Cell: CD206 - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CD3,CD3,CD3,Cell: CD3 - TRITC: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CD31,CD31,CD31,Cell: CD31 - TRITC: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CD4,CD4,CD4,Cell: CD4 - TRITC: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CD45,CD45,CD45,Cell: CD45 - TRITC: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CD45RA,CD45RA,CD45RA,Cell: CD45RA - TRITC: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CD56,CD56,CD56,Cell: CD56 - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CD68,CD68,CD68,Cell: CD68 - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CD8,CD8,CD8,Cell: CD8 - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
CK8,CK8,CK8_,Cell: CK8_ - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
DAPI,DAPI,DAPI,Cell: DAPI: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
FAP,FAP,FAP,Cell: FAP - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
FXIIIa,FXIIIa,FXIIIa,Cell: FXIIIa - FITC: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
HLADR,HLADR,HLADR,Cell: HLADR - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
HepPar1,HepPar1,HepPar1,Cell: HepPar1 - TRITC: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
Ki_67,Ki_67,Ki-67,Cell: Ki-67 - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
MPO,MPO,MPO_,Cell: MPO_ - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
NaKATPase,NaKATPase,NaKATPase,Cell: NaKATPase - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
PD_1,PD_1,PD-1,Cell: PD-1 - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
PD_L1,PD_L1,PD-L1,Cell: PD-L1 - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
VE_Cadherin,VE_Cadherin,VE-Cadherin,Cell: VE-Cadherin - TRITC: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
VEGF,VEGF,VEGF,Cell: VEGF - Cy5: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...
vimentin,vimentin,vimentin,Cell: vimentin - TRITC: Median,per_image,/Users/json/Desktop/1_Projects/251128_XYCellty...

In [22]:
# 7. Optional annotation and metadata steps.
# Remove cells in regions labelled Ignore, then assign one Sample column from
# sample annotation labels if present.

adata = qxy.remove_ignore(adata, copy=True)

sample_summary = qxy.assign_samples(adata, overwrite=True)
sample_summary

Removed cells in matching annotations
Annotation text: 'Ignore'
Annotation columns: ['annotation__Ignore']
Cells before: 727,115
Cells removed: 0
Cells after: 727,115
No sample annotation columns found matching 'annotation__*sample*'.
Created 'Sample' with None.

{'sample_col': 'Sample',
 'sample_text': 'sample',
 'annotation_columns': [],
 'sample_names': [],
 'n_assigned_cells': 0,
 'n_unassigned_cells': 727115,
 'n_conflicting_cells': 0,
 'conflict_examples': []}

In [ ]:
# # qxy.run() automatically creates CoreID from TMA Core / Parent when present.
# # Matching GeoJSON core-like labels are reported but not kept as annotation columns.

# coreid_summary = adata.uns.get("qxycell_core_ids_from_measurements")
# coreid_summary

{'target_col': 'CoreID',
 'source_cols': ['TMA Core', 'Parent'],
 'available_source_cols': ['TMA Core', 'Parent'],
 'missing_source_cols': [],
 'n_assigned_cells': 756854,
 'n_unassigned_cells': 0,
 'source_counts': {'Parent': 520460, 'TMA Core': 236394},
 'fill_only_missing': False,
 'dropped_source_cols': []}

In [23]:
# Optional sample metadata table.

metadata_path = project_dir / "sample_metadata.tsv"

if metadata_path.exists():
    metadata_summary = qxy.add_metadata(
        adata,
        metadata_path,
        sample_col="Sample",
        output_dir=output_dir,
    )
    display(metadata_summary)
else:
    print(f"No metadata table found: {metadata_path}")

No metadata table found: /Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_input/sample_metadata.tsv

In [15]:
# 8. Optional cell type logic prompt.

prompt = qxy.celltype_prompt(
    adata,
    context="Draft first-pass cell type rules for this QXYCell project.",
    print_prompt=False,
)

print(prompt[:2000])

You are helping draft a first-pass QXYCell cell type logic YAML file for spatial single-cell data imported from QuPath.

QXYCell has already loaded the project into an AnnData object. Marker positivity columns exist in `adata.obs` as `<MARKER>_pos`. Use only the marker names provided below exactly as written.

Available markers:
- CD14
- CD16
- CD1c
- CD20
- CD206
- CD3
- CD31
- CD4
- CD45
- CD45RA
- CD56
- CD68
- CD8
- CK8
- DAPI
- FAP
- FXIIIa
- HLADR
- HepPar1
- Ki_67
- MPO
- NaKATPase
- PD_1
- PD_L1
- VEGF
- VE_Cadherin
- aSMA
- vimentin

Additional biological/project context:
Draft first-pass cell type rules for this QXYCell project.

Return ONLY a valid YAML document inside a single fenced ```yaml code block.

Critical formatting requirements:
- Do not include explanatory text before or after the YAML.
- Preserve YAML indentation exactly.
- Do not convert YAML syntax into markdown bullet formatting.
- YAML list items using `-` must remain literal plain-text YAML.
- Do not use rich text formatting outside the YAML code block.

Required structure:

rules:
  - name: Example_celltype
    positive: [MARKER_A, MARKER_B]
    negative: [MARKER_C]

features:
  Example_feature:
    positive: [MARKER_A]

derived_features:
  Example_derived_feature:
    all_of: [Example_feature]

Requirements:
- Use only markers from the provided marker list.
- Rules must be ordered from most specific to most general.
- Rules are exclusive and first-match: the first matching rule assigns `celltype`.
- Put rare/specific phenotypes before broad parent populations.
- Use `positive` for required marker-positive calls.
- Use `negative` for biologically useful exclusions and to prevent broad rules from capturing specific subtypes.
- Use `any_positive` only when a cell type can be defined by any one of several markers.
- Include cautious biologically sensible immune, stromal, endothelial, tumor, proliferation, and exhaustion states only if supported by the panel.
- Do not invent markers, metadat

In [25]:
# Apply cell type logic if a YAML file has been created.

celltype_logic = output_dir / "celltype" / "celltype_logic.yaml"

if celltype_logic.exists():
    celltype_summary = qxy.celltype(
        adata,
        celltype_logic,
        celltype_dir=output_dir / "celltype",
    )
    display(celltype_summary)
else:
    print(f"Create or place a cell type YAML here when ready: {celltype_logic}")

Using QXYCell cell type logic YAML:
/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/celltype/celltype_logic.yaml
Saved cell type rule summary TSV:
/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/celltype/celltype_rules_summary_celltype_logic.tsv

{'celltype_column': 'celltype',
 'unknown_label': 'Unknown',
 'logic_source': '/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/celltype/celltype_logic.yaml',
 'n_rules': 20,
 'n_features': 0,
 'n_derived_features': 0,
 'feature_columns': [],
 'derived_feature_columns': [],
 'missing_references': ['PD1'],
 'assigned_counts': {'CD4+ T cell': 37992,
  'CD8+ T cell': 9894,
  'NK T cell': 291,
  'NK cell': 1458,
  'Macrophages': 3680,
  'B cell': 54881,
  'Conventional monocyte': 395,
  'Monocyte derived TAM': 403,
  'Dendritic cells (cDC2)': 633,
  'Immune unknown': 34017,
  'EL-CAF': 10330,
  'Endothelial cells': 22212,
  'CAF': 39356,
  'Smooth muscle cells': 11032,
  'CK8-/HepPar-': 67777,
  'Tumour cell CK8': 416177,
  'Tumour cell HepPar': 16587},
 'unknown_count': 0,
 'zero_raw_match_rules': ['CD4 PD1 T cell', 'CD8 PD1 T cell'],
 'zero_assigned_rules': ['CD4 PD1 T cell', 'CD8 PD1 T cell', 'Unknown'],
 'multi_rule_match_count': 727115,
 'rule_summary_tsv': '/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/celltype/celltype_rules_summary_celltype_logic.tsv'}

In [26]:
# 9. Basic QC.

qc_summary = qxy.qc(
    adata,
    sample_col="Sample" if "Sample" in adata.obs.columns else "Image",
    output_dir=output_dir,
)

qc_summary

Saved QXYCell QC report:
/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/qc/qc_report.html

{'output_dir': PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/qc'),
 'paths': {'overview': PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/qc/qc_overview.tsv'),
  'cells_per_sample': PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/qc/cells_per_sample.tsv'),
  'celltype_counts': PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/qc/celltype_counts.tsv'),
  'celltypes_per_sample': PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/qc/celltypes_per_sample.tsv'),
  'marker_positivity': PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/qc/marker_positivity.tsv'),
  'marker_positivity_by_sample': PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/qc/marker_positivity_by_sample.tsv'),
  'annotation_counts': PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/qc/annotation_counts.tsv'),
  'ignore_cells': PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/qc/ignore_cells.tsv'),
  'html': PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/qc/qc_report.html')},
 'tables': {'overview':                         metric     value
  0                      n_cells    727115
  1                    n_markers        28
  2                    n_samples         1
  3                   sample_col    Sample
  4                 celltype_col  celltype
  5         n_annotation_columns         6
  6    n_marker_positive_columns        28
  7  n_ignore_annotation_columns         1,
  'cells_per_sample':   Sample  n_cells
  0    nan   727115,
  'celltype_counts':                   celltype  n_cells  fraction
  0          Tumour cell CK8   416177  0.572368
  1             CK8-/HepPar-    67777  0.093214
  2                   B cell    54881  0.075478
  3                      CAF    39356  0.054126
  4              CD4+ T cell    37992  0.052250
  5           Immune unknown    34017  0.046784
  6        Endothelial cells    22212  0.030548
  7       Tumour cell HepPar    16587  0.022812
  8      Smooth muscle cells    11032  0.015172
  9                   EL-CAF    10330  0.014207
  10             CD8+ T cell     9894  0.013607
  11             Macrophages     3680  0.005061
  12                 NK cell     1458  0.002005
  13  Dendritic cells (cDC2)      633  0.000871
  14    Monocyte derived TAM      403  0.000554
  15   Conventional monocyte      395  0.000543
  16               NK T cell      291  0.000400,
  'celltypes_per_sample':    Sample                celltype  n_cells  fraction_of_sample
  0     nan                  B cell    54881            0.075478
  1     nan                     CAF    39356            0.054126
  2     nan             CD4+ T cell    37992            0.052250
  3     nan             CD8+ T cell     9894            0.013607
  4     nan            CK8-/HepPar-    67777            0.093214
  5     nan   Conventional monocyte      395            0.000543
  6     nan  Dendritic cells (cDC2)      633            0.000871
  7     nan                  EL-CAF    10330            0.014207
  8     nan       Endothelial cells    22212            0.030548
  9     nan          Immune unknown    34017            0.046784
  10    nan             Macrophages     3680            0.005061
  11    nan    Monocyte derived TAM      403            0.000554
  12    nan               NK T cell      291            0.000400
  13    nan                 NK cell     1458            0.002005
  14    nan     Smooth muscle cells    11032            0.015172
  15    nan         Tumour cell CK8   416177            0.572368
  16    nan      Tumour cell HepPar    16587            0.022812,
  'marker_positivity':          marker           column  n_positive  fraction_positive
  0          aSMA         aSMA_pos       46608           0.064100
  1          CD14         CD14_pos       51286           0.070534
  2          CD16         CD16_pos       80845           0.111186
  3          CD1c         CD1c_pos       38920           0.053527
  4          CD20         CD20_pos       95704           0.131622
  5         CD206        CD206_pos       52371           0.072026
  6           CD3          CD3_pos       69141           0.095089
  7          CD31         CD31_pos       77767           0.106953
  8           CD4          CD4_pos       72142           0.099217
  9          CD45         CD45_pos      143644           0.197553
  10       CD45RA       CD45RA_pos      125654           0.172812
  11         CD56         CD56_pos       19512           0.026835
  12         CD68         CD68_pos       91555           0.125915
  13          CD8          CD8_pos       43504           0.059831
  14          CK8          CK8_pos      438042           0.602438
  15         DAPI         DAPI_pos      709210           0.975375
  16          FAP          FAP_pos       38566           0.053040
  17       FXIIIa       FXIIIa_pos      115500           0.158847
  18        HLADR        HLADR_pos      177978           0.244773
  19      HepPar1      HepPar1_pos      269291           0.370355
  20        Ki_67        Ki_67_pos       34466           0.047401
  21          MPO          MPO_pos       33513           0.046090
  22    NaKATPase    NaKATPase_pos      398631           0.548237
  23         PD_1         PD_1_pos       17420           0.023958
  24        PD_L1        PD_L1_pos       38191           0.052524
  25  VE_Cadherin  VE_Cadherin_pos       49788           0.068473
  26         VEGF         VEGF_pos      107684           0.148098
  27     vimentin     vimentin_pos      284121           0.390751,
  'marker_positivity_by_sample':    Sample       marker           column  n_positive  fraction_positive
  0     nan         aSMA         aSMA_pos       46608           0.064100
  1     nan         CD14         CD14_pos       51286           0.070534
  2     nan         CD16         CD16_pos       80845           0.111186
  3     nan         CD1c         CD1c_pos       38920           0.053527
  4     nan         CD20         CD20_pos       95704           0.131622
  5     nan        CD206        CD206_pos       52371           0.072026
  6     nan          CD3          CD3_pos       69141           0.095089
  7     nan         CD31         CD31_pos       77767           0.106953
  8     nan          CD4          CD4_pos       72142           0.099217
  9     nan         CD45         CD45_pos      143644           0.197553
  10    nan       CD45RA       CD45RA_pos      125654           0.172812
  11    nan         CD56         CD56_pos       19512           0.026835
  12    nan         CD68         CD68_pos       91555           0.125915
  13    nan          CD8          CD8_pos       43504           0.059831
  14    nan          CK8          CK8_pos      438042           0.602438
  15    nan         DAPI         DAPI_pos      709210           0.975375
  16    nan          FAP          FAP_pos       38566           0.053040
  17    nan       FXIIIa       FXIIIa_pos      115500           0.158847
  18    nan        HLADR        HLADR_pos      177978           0.244773
  19    nan      HepPar1      HepPar1_pos      269291           0.370355
  20    nan        Ki_67        Ki_67_pos       34466           0.047401
  21    nan          MPO          MPO_pos       33513           0.046090
  22    nan    NaKATPase    NaKATPase_pos      398631           0.548237
  23    nan         PD_1         PD_1_pos       17420           0.023958
  24    nan        PD_L1        PD_L1_pos       38191           0.052524
  25    nan  VE_Cadherin  VE_Cadherin_pos       49788           0.068473
  26    nan         VEGF         VEGF_pos      107684           0.148098
  27    nan     vimentin     vimentin_pos      284121           0.390751,
  'annotation_counts':     annotation_column  n_cells  fraction
  0     annotation__HCA    22449  0.030874
  1      annotation__IM   127196  0.174932
  2  annotation__Ignore        0  0.000000
  3      annotation__NT   130006  0.178797
  4  annotation__Tonsil    69938  0.096186
  5   annotation__Tumor   160284  0.220438,
  'ignore_cells':        ignore_columns  n_ignore_cells  fraction_ignore
  0  annotation__Ignore               0              0.0}}

In [18]:
# Basic spatial plot, once a celltype column exists.

category_col = "celltype" if "celltype" in adata.obs.columns else None

if category_col is not None:
    qxy.plot_spatial(
        adata,
        sample_col="Sample" if "Sample" in adata.obs.columns else "Image",
        category_col=category_col,
        output_dir=output_dir,
        auto_figsize=True,
        save_pdf=False,
    )
else:
    print("No celltype column yet. Run cell typing before celltype spatial plots.")

No celltype column yet. Run cell typing before celltype spatial plots.

In [19]:
# 10. Save the analysis state.

h5ad_path = qxy.save(adata, output_dir=output_dir)
h5ad_path

Saved QXYCell H5AD:
/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/run/h5ad/qxycell.h5ad

PosixPath('/Users/json/Desktop/1_Projects/251128_XYCelltype_HCC_Yetong/02_outputs/run/h5ad/qxycell.h5ad')